### PR TITLE
Add rust (mingw) [CPP-120]

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Review by silverjam — COMMENTED** [review]
Looks like a good start, hopefully it compiles for windows/macos/linux once we bring in GitHub Actions support

**Comment by notoriaga** [comment]
Awesome! Got some ideas, started to work on them here - https://github.com/swift-nav/libsettings/pull/346

**Comment by silverjam** [comment]
@notoriaga close?

**Comment by notoriaga** [comment]
@silverjam yup should be fine

**Pull request closed without merging**
