### PR TITLE
let python garbage collection destroy the Settings object

### PR DESCRIPTION
**Pull request by denisng**
So... I had a thought for a minor improvement some time ago after using libsettings...

`Settings.destroy()` is not a very Pythonic way of doing object destruction, so I thought about changing the binding to `Settings.__del__()` instead.

As a side effect, I think using the `__del__()` [dunder method](https://docs.python.org/3/reference/datamodel.html?highlight=__del__#object.__del__) should allow Python's garbage collection to destroy the `Settings` object?

I do not know how to build the package so I have not been able to check if it works as envisioned...

### CODE REVIEW

**Comment by denisng** [comment]
> Is there a problem that this is trying to solve?

Not really. Just a minor enhancement that I thought of.

**Comment by silverjam** [comment]
> > Is there a problem that this is trying to solve?
> 
> Not really. Just a minor enhancement that I thought of.

Ok, we should definitely try to build and test this

**Comment by silverjam** [comment]
Ok, if you want to test this, builds are available here:

image

https://github.com/swift-nav/libsettings/actions/runs/5718998020?pr=530

**Comment by silverjam** [comment]
The builds here will be archived eventually, so if they're gone when you look for them then just re-run the "Wheels" workflow to get a new set

**Comment by denisng** [comment]
Tested OK on Intel Mac with Python 3.10:
```
/Users/denisng/opt/miniconda3/envs/libsettings/bin/python /Users/denisng/Documents/GitHub/libsettings/tests/deletion_test.py 
DEBUG:__main__:Expecting message "Building settings framework" in STDOUT...
b'Building settings framework'
DEBUG:__main__:Expecting message "Releasing settings framework" in STDOUT...
b'Releasing settings framework'

Process finished with exit code 0
```

Garbage collection seems to have triggered destruction of the `Settings` object as expected!

**Comment by denisng** [comment]
Tested OK on Ubuntu 20.04 NUC (manylinux, cp310, x86_64)

**Review by silverjam — APPROVED** [review]

**Comment by silverjam** [comment]
@denisng :shipit:

**Pull request merged**
